#!/bin/bash -eu

__prompt_color_Black='\[\e[0;30m\]'
__prompt_color_Red='\[\e[0;31m\]'
__prompt_color_Green='\[\e[0;32m\]'
__prompt_color_Yellow='\[\e[0;33m\]'
__prompt_color_Blue='\[\e[0;34m\]'
__prompt_color_Purple='\[\e[0;35m\]'
__prompt_color_Cyan='\[\e[0;36m\]'
__prompt_color_Magenta='\[\e[0;35m\]'
__prompt_color_White='\[\e[0;37m\]'

__prompt_color_BBlack='\[\e[1;30m\]'
__prompt_color_BRed='\[\e[1;31m\]'
__prompt_color_BGreen='\[\e[1;32m\]'
__prompt_color_BYellow='\[\e[1;33m\]'
__prompt_color_BBlue='\[\e[1;34m\]'
__prompt_color_BPurple='\[\e[1;35m\]'
__prompt_color_BCyan='\[\e[1;36m\]'
__prompt_color_BMagenta='\[\e[1;35m\]'
__prompt_color_BWhite='\[\e[1;37m\]'

__prompt_color_On_Black='\[\e[40m\]'
__prompt_color_On_Red='\[\e[41m\]'
__prompt_color_On_Green='\[\e[42m\]'
__prompt_color_On_Yellow='\[\e[43m\]'
__prompt_color_On_Blue='\[\e[44m\]'
__prompt_color_On_Purple='\[\e[45m\]'
__prompt_color_On_Cyan='\[\e[46m\]'
__prompt_color_On_White='\[\e[47m\]'

__prompt_color_NC='\[\e[0m\]'

 function __prompt_xtitle()
{
    case "$TERM" in
    *term* | rxvt)
        echo -en  "\e]0;$*\a" ;;
    *)  ;;
    esac
}

# Begin constructing the prompt
export PROMPT_COMMAND=__prompt_command

function prompt_history {
	echo "$__prompt_color_White[\!]"
}

function smiley_by_exit_code() {
    if [ $1 == 0 ]; then echo "😁"; else echo "🤬"; fi
}

function pwd_tail {
    pwd | awk -F/ '{nlast = NF -1;print $nlast"/"$NF}'
}

function dir_files {
	echo $(ls -1 | /usr/bin/wc -l | sed 's: ::g') files, $(ls -lah | grep -m 1 total | sed 's/total //')b
}

function cpu {
	echo "CPU $(grep 'cpu ' /proc/stat | awk '{usage=($2+$4)*100/($2+$4+$5)} END {print usage}' | awk '{printf("%.1f\n", $1)}')"%
}

function git_prompt {
	if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
        echo "-($(if_dirty_yellow_else_green)$(git_current_branch) $(git_short_commit_hash)$__prompt_color_BBlack)"
	fi
}

function git_short_commit_hash {
	echo "$(git rev-parse --short HEAD 2>/dev/null)"
}

function git_current_branch {
	echo "$(git rev-parse --abbrev-ref HEAD 2>/dev/null)"
}

function if_dirty_yellow_else_green {
	if [ -n "$(git status -s)" ]; then
		echo -e "$__prompt_color_Yellow"
	else
		echo -e "$__prompt_color_Green"
	fi
}

function aws_profile {
    if [[ ! -z "$AWS_PROFILE" ]]; then
        aws_profile_string_base="$__prompt_color_BBlack-("
        case "$AWS_PROFILE" in
            *-prod*) aws_profile_string_base+="$__prompt_color_On_Red" ;;
            *-nonprod*) aws_profile_string_base+="$__prompt_color_On_Green" ;;
            *-dev*) aws_profile_string_base+="$__prompt_color_On_Green" ;;
            *-ephemeral*) aws_profile_string_base+="$__prompt_color_On_Blue" ;;
            *personal*) aws_profile_string_base+="$__prompt_color_On_Purple" ;;
        esac
        echo "$aws_profile_string_base$__prompt_color_BWhite"AWS: "$AWS_PROFILE$__prompt_color_NC$__prompt_color_BBlack)-"
    fi
}

# Laid out to make it maximally convenient to comment out individual features of the prompt
# Prompt Escape Sequences: http://tldp.org/HOWTO/Bash-Prompt-HOWTO/bash-prompt-escape-sequences.html
function __prompt_command {
    local exit_code=$?
    __prompt_xtitle $USER@Ubuntu $(pwd)
    history -a
    PS1="$__prompt_color_NC"
    PS1+="$(prompt_history)"
    PS1+="$(aws_profile)"
    PS1+="$__prompt_color_BBlack($(smiley_by_exit_code "$exit_code")$__prompt_color_BBlack)-"
    # PS1+="($__prompt_color_BBlue\j$__prompt_color_BBlack)-" WHAT IS THIS MEANT TO DO
    # \j     the  number of jobs currently managed by the shell
    PS1+="($__prompt_color_BBlue$(pwd_tail)$__prompt_color_BBlack)-"
    PS1+="($__prompt_color_Green$(dir_files)$__prompt_color_BBlack)-"
    PS1+="($__prompt_color_Magenta$(cpu)$__prompt_color_BBlack)"
    PS1+="-(📦 $__prompt_color_Cyan$(node --version)$__prompt_color_BBlack)"
    # PS1+="-(📦 $__prompt_color_Purple$(echo v)$(npm --version)$__prompt_color_BBlack)"
    PS1+="$(git_prompt)$__prompt_color_BBlack"
    PS1+="\n"
    PS1+="$__prompt_color_Green$ "
    PS1+="$__prompt_color_NC"
}


